### ISSUE TITLE
How fast is the face detection in fps?

### ISSUE THREAD

**Issue by WuZhuoran** [rmacrae/face-detection#1]
Is this in real time on CPU or GPU? Thank you!

**Comment by rmacrae** [comment]
I've used this on a number of different platforms.  On an i7-4750HQ CPU, I am getting around 10-15 FPS.  I have also successfully run on an Nvidia Jetson TX2 at >30 FPS.  I don't have the FPS for a Nvidia desktop/server grade GPU, unfortunately.

**Comment by WuZhuoran** [comment]
@rmacrae  Thanks a lot.
